#************************* makefile for messages **************************

country    =usa-ms

#
#######################	dependencies begin here. #########################
#

all: $(country).idx

$(country).idx: $(country).msg
	-@where buildidx >nul 2>nul
	@if errorlevel 1 (echo buildidx not found; using checked-in $(country).idx) else (attrib -R $(country).msg & buildidx $(country).msg)
