#************************* makefile for messages **************************

COUNTRY    =usa-ms
country    =$(COUNTRY)

#
#######################	dependencies begin here. #########################
#

all: $(COUNTRY).idx

$(COUNTRY).idx: $(COUNTRY).msg
	@if exist "$(buildidx)" (attrib -R $(COUNTRY).msg & $(buildidx) $(COUNTRY).msg) else echo buildidx not found; using checked-in $(COUNTRY).idx
