#************************* makefile for messages **************************

COUNTRY    =usa-ms
country    =$(COUNTRY)

#
#######################	dependencies begin here. #########################
#

all: $(COUNTRY).idx

$(COUNTRY).idx: $(COUNTRY).msg
	-@where buildidx >nul 2>nul
	@if %errorlevel% neq 0 (echo buildidx not found; using checked-in $(COUNTRY).idx) else (attrib -R $(COUNTRY).msg & buildidx $(COUNTRY).msg)
