#******************** makefile for boot *****************************

msg	=..\messages
dos	=..\dos
inc	=..\inc
hinc	=..\h
COUNTRY = usa-ms

#
#################### dependencies begin here ############################
#

all: msboot.bin

boot.cl1: boot.skl \
	$(msg)\$(COUNTRY).MSG \
	makefile

msboot.obj: msboot.asm boot.cl1

msboot.bin:
	@echo Using checked-in msboot.bin and $(inc)\boot.inc
