#************************* Root level Makefile *************************

COUNTRY = usa-ms
make	=$(NMAKE) COUNTRY=$(COUNTRY)

all:
	cd messages
	$(make)
	cd ..\mapper
	$(make)
	cd ..\boot
	$(make)
	cd ..\bios
	$(make)
	cd ..\dos
	$(make)
	cd ..\cmd
	$(make)
	cd ..\dev
	$(make)
	cd ..\select
	$(make)
        cd ..\memm
        $(make)
	cd ..



