name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSVC developer environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Build
      working-directory: src
      env:
        INIT: ${{ github.workspace }}\src\TOOLS
      run: nmake /f MAKEFILE
